In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [12]:
df_raw = pd.read_csv("data/airbnb_dc_listings.csv")
print(df.shape)
df_raw.head(3)

(3723, 92)

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,7087327,https://www.airbnb.com/rooms/7087327,20151002231825,2015-10-03,Historic DC Condo-Walk to Capitol!,Professional pictures coming soon! Welcome to ...,NaN,Professional pictures coming soon! Welcome to ...,none,NaN,...,NaN,f,NaN,"DISTRICT OF COLUMBIA, WASHINGTON",f,flexible,f,f,18,NaN
1,975833,https://www.airbnb.com/rooms/975833,20151002231825,2015-10-03,Spacious Capitol Hill Townhouse,NaN,Beautifully renovated Capitol Hill townhouse. ...,Beautifully renovated Capitol Hill townhouse. ...,none,NaN,...,9.0,f,NaN,"DISTRICT OF COLUMBIA, WASHINGTON",f,strict,f,f,1,2.11
2,8249488,https://www.airbnb.com/rooms/8249488,20151002231825,2015-10-03,Spacious/private room for single,This is an ideal room for a single traveler th...,NaN,This is an ideal room for a single traveler th...,none,NaN,...,NaN,f,NaN,NaN,f,flexible,f,f,1,1.00

There are 92 columns, so keeping only the ones I'm analyzing:

- host_response_rate: the response rate of the host
- host_acceptance_rate: number of requests to the host that convert to rentals
- host_listings_count: number of other listings the host has
- latitude: latitude dimension of the geographic coordinates
- longitude: longitude part of the coordinates
- city: the city the living space resides
- zipcode: the zip code the living space resides
- state: the state the living space resides
- accommodates: the number of guests the rental can accommodate
- room_type: the type of living space (Private room, Shared room or Entire home/apt
- bedrooms: number of bedrooms included in the rental
- bathrooms: number of bathrooms included in the rental
- beds: number of beds included in the rental
- price: nightly price for the rental
- cleaning_fee: additional fee used for cleaning the living space after the guest leaves
- security_deposit: refundable security deposit, in case of damages
- minimum_nights: minimum number of nights a guest can stay for the rental
- maximum_nights: maximum number of nights a guest can stay for the rental
- number_of_reviews: number of reviews that previous guests have left

In [11]:
cols_to_keep = ["host_response_rate", "host_acceptance_rate", "host_listings_count",
               "latitude", "longitude", "city", "zipcode", "state", "accommodates",
               "room_type", "bedrooms", "bathrooms", "beds", "price", "cleaning_fee", 
               "security_deposit", "minimum_nights", "maximum_nights", "number_of_reviews"]

In [13]:
df = df_raw[cols_to_keep]
print(df.shape)
df.head(3)

(3723, 19)

,host_response_rate,host_acceptance_rate,host_listings_count,latitude,longitude,city,zipcode,state,accommodates,room_type,bedrooms,bathrooms,beds,price,cleaning_fee,security_deposit,minimum_nights,maximum_nights,number_of_reviews
0,92%,91%,26,38.890046,-77.002808,Washington,20003,DC,4,Entire home/apt,1.0,1.0,2.0,$160.00,$115.00,$100.00,1,1125,0
1,90%,100%,1,38.880413,-76.990485,Washington,20003,DC,6,Entire home/apt,3.0,3.0,3.0,$350.00,$100.00,NaN,2,30,65
2,90%,100%,2,38.955291,-76.986006,Hyattsville,20782,MD,1,Private room,1.0,2.0,1.0,$50.00,NaN,NaN,2,1125,1

In [16]:
df.iloc[0]["accommodates"]

4